const menuRoot=document.querySelector('#menu'),categoryList=document.querySelector('#category-list'),search=document.querySelector('#search'),empty=document.querySelector('#empty');
const escapeHtml=s=>s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const icon={meat:'⌁',hot:'♨',salads:'❋',sides:'◇',sauces:'◒',bread:'▱',drinks:'◉'};
function nav(){categoryList.innerHTML=menu.map((g,i)=>`<a href="#${g.id}" class="${i?'':'active'}" data-id="${g.id}"><b>${icon[g.id]}</b><span>${g.category}</span></a>`).join('')}
function render(query=''){
 const q=query.trim().toLocaleLowerCase('ru'); let count=0;
 menuRoot.innerHTML=menu.map(group=>{const items=group.items.filter(x=>x.name.toLocaleLowerCase('ru').includes(q));count+=items.length;if(!items.length)return'';
 return `<section class="menu-section" id="${group.id}" data-section><header><h2>${group.full}</h2>${group.note?`<p>${group.note}</p>`:''}</header><div class="dish-list">${items.map((item,index)=>{const priority=group.id==='meat'&&index<4,filename=item.image.split('/').pop();return `<button class="dish" type="button" data-name="${escapeHtml(item.name)}" data-weight="${escapeHtml(item.weight)}" data-price="${escapeHtml(item.price||'')}" data-image="${item.image}" data-tone="${item.tone}"><span class="dish-image ${item.tone}" role="img" aria-label="${escapeHtml(item.name)}"><img src="assets/images/menu/320/${filename}" srcset="assets/images/menu/320/${filename} 320w, assets/images/menu/640/${filename} 640w, ${item.image} 960w" sizes="(max-width: 599px) 112px, 130px" alt="" width="224" height="184" loading="${priority?'eager':'lazy'}" decoding="async" fetchpriority="${priority?'high':'low'}" onerror="this.hidden=true"></span><span class="dish-info"><strong>${escapeHtml(item.name)}</strong>${item.weight?`<small>${escapeHtml(item.weight)}</small>`:''}${item.price?`<em>${escapeHtml(item.price)}</em>`:''}</span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 5 7 7-7 7"></path></svg></button>`}).join('')}</div></section>`}).join('');empty.hidden=count>0;observeSections();
}
menuRoot.addEventListener('click',event=>{const dish=event.target.closest('.dish');if(dish)openSheet(dish.dataset)});
const dialog=document.querySelector('#dialog'),title=document.querySelector('#sheet-title'),meta=document.querySelector('#sheet-meta'),sheetImage=document.querySelector('#sheet-image'),closeButton=document.querySelector('#close-dialog');let savedScroll=0;
function openSheet(d){savedScroll=window.scrollY;title.textContent=d.name;meta.textContent=[d.weight,d.price].filter(Boolean).join(' · ');meta.hidden=!meta.textContent;sheetImage.className=`sheet-image ${d.tone}`;sheetImage.style.backgroundImage=`url("${d.image}")`;sheetImage.setAttribute('aria-label',d.name);dialog.classList.add('open');dialog.setAttribute('aria-hidden','false');document.body.classList.add('locked');document.body.style.top=`-${savedScroll}px`;closeButton.focus()}
function closeSheet(){dialog.classList.remove('open');dialog.setAttribute('aria-hidden','true');document.body.classList.remove('locked');document.body.style.top='';window.scrollTo(0,savedScroll)}
closeButton.addEventListener('click',closeSheet);document.querySelector('.dialog-backdrop').addEventListener('click',closeSheet);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&dialog.classList.contains('open'))closeSheet()});
search.addEventListener('input',e=>render(e.target.value));categoryList.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;e.preventDefault();document.querySelector(a.hash)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});});
let observer;function observeSections(){observer?.disconnect();observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){document.querySelectorAll('.categories a').forEach(a=>a.classList.toggle('active',a.dataset.id===e.target.id));document.querySelector(`.categories a[data-id="${e.target.id}"]`)?.scrollIntoView({inline:'center',block:'nearest'})}}),{rootMargin:'-35% 0px -55%'});document.querySelectorAll('[data-section]').forEach(s=>observer.observe(s))}
const topButton=document.querySelector('#to-top');addEventListener('scroll',()=>topButton.classList.toggle('visible',scrollY>650),{passive:true});topButton.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));document.querySelector('.header-button').addEventListener('click',()=>document.querySelector('.menu-tools').scrollIntoView({behavior:'smooth'}));nav();render();
